### ISSUE TITLE
Release 2.x to Play Store

### ISSUE THREAD

**Issue by Sardtok** [matburt/mobileorg-android#490]
There have been two 2.x releases, yet the Play Store is still on the old 0.9.13 release.

**Comment by wizmer** [comment]
This is normal. I don't have the Play Store credentials. I have asked them to the former maintainer and I am waiting for his reply. 

If he does not answer I'll have to release the app under a different name but that would be inconvenient I think...

**Comment by ssefick** [comment]
First, thank you for this very interesting project that I will probably use everyday. Second,I have a couple of concerns as a new emacs/MobileOrg user.

I noticed that there is no longer a need for emacs to use this app. If emacs is not a part of the workflow, I would suggest releasing under a different name.

Can this new version still be used like the old version using both a PC emacs (org-mobile-push, etc.) and MobileOrg (linked to google cal)? I am starting to really enjoy the old app, and do not want to lose this functionality.

**Comment by wizmer** [comment]
It depends what you mean by "like the old version".
A git repo is no more than a folder. You can open files in there and modify them. Once you're done with your changes, you can propagate them by doing "git push". If you set emacs org-mobile-push function to "git push" and org-mobile-pull to "git pull", you'll have exactly the same functionality.

About the Google Cal, it's a feature I disabled because I had no time for the maintenance of this until now. But it is one of the most important feature so it is definitely coming back.
